server.port=9000
api.security.token.secret=${JWT_SECRET:suXd42tATzbN/ewjV6NVY0Ug2edcOGSpLYctfxS7tLE=}

spring.mail.host=in-v3.mailjet.com
spring.mail.port=587
spring.mail.username=16b188090a34865c0cecd8ec53e37eae
spring.mail.password=4ea1539deff383b0fc3bed96a873d0c2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.remetente=luizfelipemurarolli@gmail.com